### ISSUE TITLE
Feedback on latest iteration

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/dist-design#12]
Looks great overall!

Outputs:
* Regarding `fn write(step: Step, output: Vec<ZSet> -> Result<()>`. Are steps part of the public interface to a client? That is, are steps the idempotency key for output consumers?

Coordinator:
* versions(): each worker can have at most 2 versions, right? This will need an initial version 0 with an empty DB at all workers to avoid the empty set intersection fatal error during bootstrap.

Rolling upgrades (both scale in-out and layout change options):
* I assume inputs go to both worker-versions when this happens? And if so, would intermediate shuffles/exchanges potentially share data from higher versioned processes to lower versions?

**Comment by blp** [comment]
> * Regarding `fn write(step: Step, output: Vec<ZSet> -> Result<()>`. Are steps part of the public interface to a client? That is, are steps the idempotency key for output consumers?

It can be, if that's convenient. For Kafka output, the step numbers could be put into headers that can be attached to Kafka messages.

> * versions(): each worker can have at most 2 versions, right? This will need an initial version 0 with an empty DB at all workers to avoid the empty set intersection fatal error during bootstrap.

Yes, I tried to capture that with:

```
  * A new database has only one version, numbered 0, which is empty.
```

> * I assume inputs go to both worker-versions when this happens? And if so, would intermediate shuffles/exchanges potentially share data from higher versioned processes to lower versions?

Yes and yes. If the versions aren't compatible enough for that then I don't know how to do rolling upgrade.

**Comment by lalithsuresh** [comment]
I plan to eventually add some integration tests for testing upgrades from the last release version (or a few) to any given commit. Hopefully this well help you test rolling upgrade tests too.

If we release a breaking change, then the upgrade can't be a rolling one but has to require a full pipeline restart I assume. Which is fine to do occasionally.
