### ISSUE TITLE
Questions re FT algorithm

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dist-design#7]
> Put data into the circuit for this step. First, attempt to read one event from each partition in workers from step:

Here and below, it would help to explicitly specify the offset at which we read. Is it `seq` here?

> If we get an event for one or more of the workers, then we're replaying the log after restarting. In this case, there will normally be an event for all of the workers but, if there was a failure, we might have an event in only some of them. To handle that, we write an event to each partition that lacked one. It's easiest to just fill them in as "empty", indicating that no data is to be included in those workers for this step, and it seems like we might as well do that because this case occurs at most once per program run.

Does this mean that each host must read _all_ partitions of `step`, determine that at least one of them has an entry for `seq` and write empty entries for its local workers that don't have entries in `step`?

> For k in 0..K, for w in workers, write data from output handle k in worker w to partition w of output[k], unless that output was already produced in a previous run.

How do we determine whether the output was produced?

> Read one event from step for each partition where we didn't already read one in step 1 above, blocking as necessary. Also block until our own write or writes to step commit.

Are we reading at offset `seq` still? In step 1 we either read an event from _all_ partitions if we're in the recovery mode (thanks to the fact that we write empty events where there wasn't one) or none (if we're running normally), so I'm not sure which events we're reading here.

**Comment by blp** [comment]
Good questions. I'm working on clarifying.

**Comment by blp** [comment]
> > Put data into the circuit for this step. First, attempt to read one event from each partition in workers from step:
> 
> Here and below, it would help to explicitly specify the offset at which we read. Is it `seq` here?

Yes.

I will clarify with something like this:
```patch
diff --git a/README.md b/README.md
index 290e9a7..d37637b 100644
--- a/README.md
+++ b/README.md
@@ -201,10 +201,24 @@ On each worker:
 - Open a transaction on the state database (if one isn't already
   open).
   
-Then on the host, for `seq` in `start_seq..`:
+- Seek `consumer` in every partition of `step` to `start_seq`.  This
+  is either the offset of an event that exists, or just past the end.
+  If it's later than that, or if it's so early that Kafka already
+  expired it, that's a fatal error.
+  
+- Seek `consumer` in every subscribed partition of `input[*]` to the
+  position that corresponds to `start_seq`.  (To find this position,
+  we actually need to read the event with event offset `start_seq - 1`
+  in `step`.)
+  
+Then on the host, for `seq` in `start_seq..`, repeat the following.
+At the beginning of each iteration, `consumer` is positioned at event
+offset `seq` in every partition of `step` and at the offset
+corresponding to `seq` in the subscribed partitions in `input[*]`.
 
 1. Put data into the circuit for this step.  First, attempt to read
-   one event from each partition in `workers` from `step`:
+   one event from each partition in `workers` from `step`, to obtain
+   the input step size for `seq`:
 
    * If we get an event for one or more of the workers, then we're
      replaying the log after restarting.  In this case, there will
```

**Comment by blp** [comment]
> > If we get an event for one or more of the workers, then we're replaying the log after restarting. In this case, there will normally be an event for all of the workers but, if there was a failure, we might have an event in only some of them. To handle that, we write an event to each partition that lacked one. It's easiest to just fill them in as "empty", indicating that no data is to be included in those workers for this step, and it seems like we might as well do that because this case occurs at most once per program run.
> Does this mean that each host must read _all_ partitions of `step`, determine that at least one of them has an entry for `seq` and write empty entries for its local workers that don't have entries in `step`?

This is written in a less than perfectly clear way. I will add clarifications here and elsewhere about my intent. In particular, I'm adding here:

```markdown
     Afterward, our consumer in `input-step` is at offset `seq + 1` in
     the partitions in `workers`, and `seq` in the rest.
```

(note that I'm renaming `step` to `input-step`)

But I'm also going back and adding some background material on how I'm thinking about how steps are triggered:

```markdown
## Triggering DBSP steps

DBSP steps work on batches of input data.  The workers must agree when
to trigger a step.  Two approaches come to mind:

* **Centralized trigger**, in which a coordinator tells each host to
  trigger a step and how much data to include in the step.  To trigger
  a step, the coordinator produces an event to each partition in
  `input-step`, and each host consumes the partitions for its own
  workers.

  With this approach, it is conceptually simple to trigger a step
  based on properties that span all the workers, such as "`input[0]`
  received at least 1000 events total across all its partitions".

  This approach does not seem well suited for Kafka, because Kafka
  does not appear to support monitoring a partition for new data
  without reading the data from that partition.  Thus, a coordinator
  that wanted to evaluate a property like the one above would have to
  consume all of the data from all of partitions in `input[0]`, which
  would be a bottleneck.  (Kafka would allow a coordinator to
  periodically poll all the partitions for new data without consuming
  it, so this could

* **Distributed trigger**, in which each host waits until it is
  independently ready to trigger a step.  When a host is ready, it
  produces an event into the partitions for its workers in
  `input-step`.  Each host also waits for other hosts to produce
  events into their partitions and, as soon as any one of them does,
  it produces an event into the partitions for its own workers.  Thus,
  a step begins as soon as any one of the hosts is ready.

  In this approach, it is hard to step based on a property that spans
  all the workers.  To do so, one could introduce extra communication
  among the hosts or with a coordinator.

  This approach should work well with Kafka.  All the hosts need to
  consume all of the partitions in `input-step`, but this should not
  increase network traffic very much because their events should be
  small arrays of event offsets.

We adopt the distributed trigger approach for the reasons described
above.
```
 
> > For k in 0..K, for w in workers, write data from output handle k in worker w to partition w of output[k], unless that output was already produced in a previous run.
> 
> How do we determine whether the output was produced?

I'm adding this in the list of variables:

```markdown
* `output_tail[*]`, a `K`-element vector.  Each element of
  `output_tail[k]` is a map from each worker `w` in `workers` to the
  sequence number of the last step that appears in `output[k]` in
  partition `w`.  (These can be obtained by reading the sequence
  number header in the last event in each partition in `output[k]`.)
```

and then clarifying what you quoted as:

```markdown
6. For `k` in `0..K`, for `w` in `workers`, write data from output
   handle `k` in worker `w` to partition `w` of `output[k]`, unless
   `seq <= output_tail[k][w]`[^2].

[^2]: If `seq <= output_tail[k][w]`, then this output was already
produced in a previous run.  DBSP is designed to produce deterministic
output, so in this case we could read the old output and compare it
against the new and issue a warning or a fatal error if it differs.
```

> > Read one event from step for each partition where we didn't already read one in step 1 above, blocking as necessary. Also block until our own write or writes to step commit.
> 
> Are we reading at offset `seq` still? In step 1 we either read an event from _all_ partitions if we're in the recovery mode (thanks to the fact that we write empty events where there wasn't one) or none (if we're running normally), so I'm not sure which events we're reading here.

I'm adding some material on a precondition for the loop iteration (all the consumers are positioned at `seq`) and then clarifying the text you quoted as:

```markdown
7. Our consumer in `input-step` is at offset `seq + 1` in some
   partitions and may be at offset `seq` in others.  In the partitions
   where we're at offset `seq`, if any, read one event, blocking as
   necessary.  Afterward, the consumer is now at offset `seq + 1` in
   every partition.
```

**Comment by blp** [comment]
I think the changes I pushed address your feedback.
