### ISSUE TITLE
Minor thing about RocksDB

### ISSUE THREAD

**Issue by gz** [feldera/dist-design#8]
https://github.com/feldera/dist-design/blob/85291465e4b4b6c6b2e528df89ef848de3f9199e/rocksdb.md?plain=1#L18

I reported this bug a while ago to rocksdb https://github.com/facebook/rocksdb/issues/5117#issuecomment-1647381292
but meanwhile, a PR to fix this has appeared: https://github.com/facebook/rocksdb/pull/11269

**Comment by blp** [comment]
I'm closing this because we aren't using RocksDB anymore.
